In [60]:
import ANNNIstates
import numpy as np

In [56]:
data_path = '../tensor_data/'

In [58]:
tensorini = ANNNIstates.mps() # load the folder

In [59]:
print("Here are all the information obtained from the folder:")
print(f' L = {tensorini.L}\n\n hs = {tensorini.hs:}\n hs (precision) = {tensorini.h_prec}\n\n ks = {tensorini.ks}\n ks (precision) = {tensorini.k_prec}')

Here are all the information obtained from the folder:
 L = 12

 hs = [0.   0.1  0.11 0.2  0.21 0.3  0.32 0.4  0.42 0.5  0.53 0.6  0.63 0.7
 0.74 0.8  0.84 0.9  0.95 1.   1.05 1.1  1.16 1.2  1.26 1.3  1.37 1.4
 1.47 1.58 1.68 1.79 1.89 2.  ]
 hs (precision) = 2

 ks = [0.   0.05 0.1  0.11 0.15 0.16 0.2  0.21 0.25 0.26 0.3  0.32 0.35 0.37
 0.4  0.42 0.45 0.47 0.5  0.53 0.55 0.58 0.6  0.63 0.65 0.68 0.7  0.74
 0.75 0.79 0.8  0.84 0.85 0.89 0.9  0.95 1.  ]
 ks (precision) = 2


In [7]:
# I can also easily load the files
print(f'SHAPE:\n {np.loadtxt(ANNNIstates.tensor_str(0,0))}\n')
print(f'TENS:\n {np.loadtxt(ANNNIstates.shape_str(0,0))}')


SHAPE:
 [-0.70710678  0.70710678 -0.70710678  0.70710678 -0.70710678  0.70710678
 -0.70710678  0.70710678 -0.70710678  0.70710678  0.70710678 -0.70710678
 -0.70710678  0.70710678  0.70710678 -0.70710678  0.70710678 -0.70710678
 -0.70710678  0.70710678 -0.70710678  0.70710678 -0.70710678  0.70710678]

TENS:
 [[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]
