# Noteboks: how are the states stored?

In [1]:
import sys 
sys.path.append('../src')

import ANNNIstates 
import numpy as np

In [8]:
# Folder where all the filesare stored
data_path = '../tensor_data/'

# Load all files with ANNNIstates.mps class
tensorini = ANNNIstates.mps(folder = data_path)

/home/saverio/Desktop/ANNNI2/.venv/lib/python3.10/site-packages/numpy/core/numeric.py:330: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')


In [3]:
print("Here are all the information obtained from the folder:")
print(f' L = {tensorini.L}\n\n hs = {tensorini.hs:}\n hs (precision) = {tensorini.h_prec}\n\n ks = {tensorini.ks}\n ks (precision) = {tensorini.k_prec}')

Here are all the information obtained from the folder:
 L = 12

 hs = [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2. ]
 hs (precision) = 2

 ks = [0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]
 ks (precision) = 2


In [5]:
# Loading all the files can be done easily
print(f'SHAPE:\n {np.loadtxt(tensorini.tensor_str(0,0))}\n')
print(f'TENS:\n {np.loadtxt(tensorini.shape_str(0,0))}')


SHAPE:
 [-0.70710678  0.70710678 -0.70710678  0.70710678 -0.70710678  0.70710678
 -0.70710678  0.70710678 -0.70710678  0.70710678  0.70710678 -0.70710678
 -0.70710678  0.70710678  0.70710678 -0.70710678  0.70710678 -0.70710678
 -0.70710678  0.70710678 -0.70710678  0.70710678 -0.70710678  0.70710678]

TENS:
 [[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]
